version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    env_file:
      - .env
    volumes:
      - ./:/app
  mysql:
    image: bitnami/mysql:5.7
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: food_delivery
      MYSQL_PASSWORD: fo0d_d3l1v3ry
      MYSQL_DATABASE: food_delivery
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
